AWSTemplateFormatVersion: "2010-09-09"

Description: >
    My First Standalone CFN Template

Resources:

    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/20
            EnableDnsSupport: true
            Tags:
                - Key: Name
                  Value: GrantVPC
