AWSTemplateFormatVersion: "2010-09-09"
Description: >
    Deploys an ECS Cluster + an Application Load Balancer

Parameters:
    NetworkStackName:
        Type: String
        Description: Name of the network stack
        Default: granta-network

    GrantAzureComHostedZoneId:
        Type: String
        Description: Hosted Zone ID of grantazure.com
        Default: ZPWT7V1HN6HH9

Resources:

    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId:
                Fn::ImportValue: !Sub ${NetworkStackName}-vpc-id
            GroupDescription: Inbound HTTP/S
            SecurityGroupIngress:
                - FromPort: 80
                  ToPort: 80
                  IpProtocol: tcp
                  CidrIp: "0.0.0.0/0"
                - FromPort: 443
                  ToPort: 443
                  IpProtocol: tcp
                  CidrIp: "0.0.0.0/0"

    ALB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Type: application
            SecurityGroups:
                - !Ref LoadBalancerSecurityGroup
            Subnets:
                Fn::Split:
                    - ","
                    - Fn::ImportValue: !Sub "${NetworkStackName}-public-subnets"

    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            VpcId:
                Fn::ImportValue: !Sub ${NetworkStackName}-vpc-id
            Port: 80
            Protocol: HTTP

    HTTPListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref ALB
            Port: 80
            Protocol: HTTP
            DefaultActions:
                - TargetGroupArn: !Ref DefaultTargetGroup
                  Type: forward

    DNSRecord:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref GrantAzureComHostedZoneId
            Comment: DNS For my ALB
            Name: "api.grantazure.com"
            Type: CNAME
            TTL: 900
            ResourceRecords:
                - !GetAtt ALB.DNSName

    ECSCluster:
        Type: AWS::ECS::Cluster

    ECSExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: "ecs-tasks.amazonaws.com"
                      Action:
                        - sts:AssumeRole

    ECSExecutionRolePolicy:
        Type: AWS::IAM::Policy
        Properties:
            Roles:
                - !Ref ECSExecutionRole
            PolicyName: !Sub ${AWS::StackName}-ecs-execution-role-policies
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Resource: "*"
                      Action:
                        - ecr:GetAuthorizationToken
                        - ecr:BatchCheckLayerAvailability
                        - ecr:GetDownloadUrlForLayer
                        - ecr:BatchGetImage
                        - logs:CreateLogStream
                        - logs:PutLogEvents

    ECSServiceSchedulerRole:
        Type: AWS::IAM::Role
        Properties:
            Path: "/"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: "ecs.amazonaws.com"
                      Action:
                        - sts:AssumeRole

    ECSServiceSchedulerRolePolicy:
        Type: AWS::IAM::Policy
        Properties:
            Roles:
                - !Ref ECSServiceSchedulerRole
            PolicyName: !Sub ${AWS::StackName}-ecs-service-scheduler-role-policies
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Resource: "*"
                      Action:
                        - ec2:AuthorizeSecurityGroupIngress
                        - ec2:Describe*
                        - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
                        - elasticloadbalancing:DeregisterTargets
                        - elasticloadbalancing:Describe*
                        - elasticloadbalancing:RegisterInstancesWithLoadBalancer
                        - elasticloadbalancing:RegisterTargets

Outputs:
    HTTPListerArn:
        Value: !Ref HTTPListener
        Export:
            Name: !Sub ${AWS::StackName}-http-listener-arn

    ECSExecutionRoleArn:
        Value: !GetAtt ECSExecutionRole.Arn
        Export:
            Name: !Sub ${AWS::StackName}-ecs-execution-role-arn

    ECSServiceSchedulerRoleArn:
        Value: !GetAtt ECSExecutionRole.Arn
        Export:
            Name: !Sub ${AWS::StackName}-ecs-service-scheduler-role-arn

    ECSClusterName:
        Value: !Ref ECSCluster
        Export:
            Name: !Sub ${AWS::StackName}-ecs-cluster-name

